// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoqbhzlmpubwdiaoswei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcWJoemxtcHVid2RpYW9zd2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDAzNjcsImV4cCI6MjA1NDY3NjM2N30.zmypdCIo7XjrtaNz9BRhkfaBk5lKS6S2aQtPg3ozlJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);